name: Release Chinese Kenan Modpack

on: 
  workflow_dispatch:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '0 0 * * *'

jobs:
  deploy:
    environment: Translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'

#       - name: 拉取 Kenan 最新内容 by Merge from Upstream Repository
#         continue-on-error: true
#         # rebase 太慢了
#         uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
#         with:
#           upstream_repository: Kenan2000/CDDA-Kenan-Modpack
#           upstream_branch: master
#           target_branch: master

      - uses: actions/checkout@v2

      - name: Install Dependency
        run: npm install

      - name: 拉取 Paratranz 最新内容
        run: npm run import-paratranz
        env:
          PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
      - name: Build Mod
        run: npm start
        env:
          BAIDU_TRANSLATION_APP_ID: ${{ secrets.BAIDU_TRANSLATION_APP_ID }}
          BAIDU_TRANSLATION_SECRET: ${{ secrets.BAIDU_TRANSLATION_SECRET }}
          SOUGOU_TRANSLATION_APP_ID: ${{ secrets.SOUGOU_TRANSLATION_APP_ID }}
          SOUGOU_TRANSLATION_SECRET: ${{ secrets.SOUGOU_TRANSLATION_SECRET }}
      - name: Build Wiki
        run: npm run build-wiki

      - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r Kenan-Modpack-Mod汉化版.zip Kenan-Modpack-Chinese/ 汉化说明.txt

      - name: Get build timestamp
        id: get-timestamp
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HHmm'
      - name: Echo environmental variables
        id: generate_env_vars
        run: |
          echo "archive-${{ steps.get-timestamp.outputs.time }}"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            Kenan-Modpack-Mod汉化版.zip
          name: 'CDDA-Kenan-Mod合集汉化版 ${{ steps.get-timestamp.outputs.time }} 测试包'
          tag_name: ${{ steps.get-timestamp.outputs.time }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    
      - name: Deploy Tiddlywiki
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public-dist
          
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          message: 'feat: 自动拉取Paratranz最新内容并发布'
#           pull_strategy: NO-PULL
